repos:
-   repo: https://github.com/biomejs/pre-commit
    rev: "v2.2.6"
    hooks:
    -   id: biome-format
        additional_dependencies: ["@biomejs/biome@2.2.6"]
-   repo: local
    hooks:
    -   id: build
        name: Build project
        entry: pnpm build
        language: system
        pass_filenames: false
        always_run: false
    -   id: test
        name: Run tests
        entry: pnpm test
        language: system
        pass_filenames: false
        always_run: false

